//Constants
export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
export const SORT_CARS = 'CarList/SORT_CARS';
export const GET_CARS_LIST = 'CarList/GET_CARS_LIST';
export const GET_CARS_LIST_SUCCESS = 'CarList/GET_CARS_LIST_SUCCESS';
export const GET_CARS_LIST_FAILURE = 'CarList/GET_CARS_LIST_FAILURE';
export const SET_COLOR_NAME = 'CarList/SET_COLOR_NAME';
export const SET_MANUFACTORER = 'CarList/SET_MANUFACTORER';
export const GET_COLORS = 'CarList/GET_COLORS';
export const GET_COLORS_SUCCESS = 'CarList/GET_COLORS_SUCCESS';
export const GET_COLORS_FAILURE = 'CarList/GET_COLORS_FAILURE';
export const GET_MANUFACTORERS = 'CarList/GET_MANUFACTORERS';
export const GET_MANUFACTORERS_SUCCESS = 'CarList/GET_MANUFACTORERS_SUCCESS';
export const GET_MANUFACTORERS_FAILURE = 'CarList/GET_MANUFACTORERS_FAILURE';
export const GET_CAR_DETAILS = 'CarList/GET_CAR_DETAILS';
export const GET_CAR_DETAILS_SUCCESS = 'CarList/GET_CAR_DETAILS_SUCCESS';
export const GET_CAR_DETAILS_FAILURE = 'CarList/GET_CAR_DETAILS_FAILURE';
